server:
  port: 8082

spring:
  application:
    name: HOTELS-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/microservices?useUnicode=yes&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: ieytsak7eq@123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect


eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

        
okta:
  oauth2:
    issuer: https://dev-23466193.okta.com/oauth2/default
    audience: api://default