server:
  port: 8081
spring:
  application:
    name: USER-SERVICE
  config:
   import: optional:configserver:http://localhost:8085
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri:  https://dev-23466193.okta.com/oauth2/default
      client:
        registration:
          my-internal-client:
            provider: okta
            authorization-grant-type: client_credentials
            scope: internal
            client-id: 0oah7p1lq9cOUFCyg5d7
            client-secret: B2uNr2kvg8wFS36zyWMPW_rcOukAgP5JmpuoB47kcxIcJ-MPq0_69rP4Iss5WVsH
  datasource:
    url: jdbc:mysql://localhost:3306/microservices?useUnicode=yes&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: ieytsak7eq@123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  profiles:
   active: prod

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health

  endpoint:
    health:
      show-details: always




resilience4j:
  circuitbreaker:
    instances:
      ratingHotelBreaker:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 6s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED

  retry:
    instances:
      ratingHotelService:
        max-attempts: 3
        wait-duration: 5s

  ratelimiter:
    instances:
      userRateLimiter:
        limit-refresh-period: 4s
        limit-for-period: 1
        timeout-duration: 1s
        
okta:
  oauth2:
    issuer: https://dev-23466193.okta.com/oauth2/default
    audience: api://default
 
#
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka
      
#management:
#  health:
#    circuitbreakers:
#      enabled: true
#  endpoints:
#    web:
#      exposure:
#        include: health
#
#  endpoint:
#    health:
#      show-details: always
#
#
#
#resilience4j:
#  circuitbreaker:
#    instances:
#      ratingHotelBreaker:
#        registerHealthIndicator: true
#        eventConsumerBufferSize: 10
#        failureRateThreshold: 50
#        minimumNumberOfCalls: 5
#        automaticTransitionFromOpenToHalfOpenEnabled: true
#        waitDurationInOpenState: 6s
#        permittedNumberOfCallsInHalfOpenState: 3
#        slidingWindowSize: 10
#        slidingWindowType: COUNT_BASED
#
#  retry:
#    instances:
#      ratingHotelService:
#        max-attempts: 3
#        wait-duration: 5s
#
#  ratelimiter:
#    instances:
#      userRateLimiter:
#        limit-refresh-period: 4s
#        limit-for-period: 2
#        timeout-duration: 2s
#

#
#
#
#
#
#
#
#
#
#
